### ISSUE TITLE
OSX10.10.3Yosemite下点击公众文章中连接报错加卡死

### ISSUE THREAD

**Issue by Yaccc** [geeeeeeeeek/electronic-wechat#54] opened 2016-03-03 11:04 UTC
![image](https://cloud.githubusercontent.com/assets/5906306/13492387/ae3c1c90-e172-11e5-8a95-5ee3088c85a1.png)

**Comment by geeeeeeeeek** [comment] 2016-03-03 11:29
Duplicate of #30.

**Closed by geeeeeeeeek** 2016-03-03 11:29 UTC
