### ISSUE TITLE
The application can open more than one window, and when I '@' someone,it just send a '@' character, the nickname lost 

### ISSUE THREAD

**Issue by niuzhiqiang90** [geeeeeeeeek/electronic-wechat#124] opened 2016-04-11 10:28 UTC
#First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description
The application can open more than one window, and when I '@' someone,it just send a '@' character, the nickname lost 

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`  
```
$ electron --version
command not found
```
```
- Version of Node.js (run `$ node --version`): `v4.3.0`
- OS: `<Ubuntu 14.04.4 64bit>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
![selection_041](https://cloud.githubusercontent.com/assets/17499068/14423964/16c106d8-0011-11e6-8bb4-ca3e37468703.png)

![selection_043](https://cloud.githubusercontent.com/assets/17499068/14423965/16c1271c-0011-11e6-9965-0f660ab9be01.png)

**Comment by geeeeeeeeek** [comment] 2016-04-11 12:59
I'll look into that.

**Comment by geeeeeeeeek** [comment] 2016-04-12 07:24
@niuzhiqiang90 Thx for your feedback. This is caused by angular's digest cycle.

Issue has been fixed in [master](https://github.com/geeeeeeeeek/electronic-wechat/commit/6837bd572f14960ed3fdfa4e16a6d9507e14e2ba). Plz check out.


#### Fix issues releated to mention menu.
1. Fix cursor position after a user is selected, which would jump to the first character after a user. This is resolved due to the change of implementation. Now use insertToEditArea providede by angular scope instead.
2. Fix message sent right after a user is selected, which would cause inserted user name not digested by angular and would not be included into the message text.

**Closed by geeeeeeeeek** 2016-04-12 07:24 UTC
Labels: bug
